# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('boton', models.CharField(max_length=20)),
                ('URL', models.URLField()),
                ('color_del_boton', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloCodigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('boton', models.CharField(max_length=20)),
                ('color_del_boton', models.CharField(max_length=20)),
                ('codigo', models.TextField(max_length=500)),
                ('URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuloImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('URL', models.URLField()),
                ('nombre_del_URL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('nombre_del_URL', models.CharField(max_length=100)),
                ('URL', models.URLField()),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=40)),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('boton', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='moduloitem',
            name='moduloproductos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ModuloProductos'),
        ),
    ]
