# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=20)),
                ('img', models.ImageField(height_field='607', upload_to=b'', width_field='363')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('boton', models.CharField(max_length=20)),
                ('img', models.ImageField(height_field='600', upload_to=b'', width_field='363')),
            ],
        ),
    ]
