# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pagina2_pagina3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=40)),
                ('bg', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=20)),
                ('icon', models.ImageField(height_field='50', upload_to=b'', width_field='50')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('boton', models.CharField(max_length=20)),
                ('icon', models.ImageField(height_field='75', upload_to=b'', width_field='75')),
            ],
        ),
    ]
