# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pagina4_pagina5_pagina6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina2',
            name='img',
        ),
        migrations.RemoveField(
            model_name='pagina3',
            name='img',
        ),
    ]
