# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180420_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('URL', models.URLField(max_length=300)),
                ('nombre_del_URL', models.CharField(max_length=100)),
            ],
        ),
    ]
