# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_modulopie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('d', 'Borrador'), ('p', 'Publicado'), ('r', 'Review'), ('t', 'Basura')], max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
