# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180412_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina4',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='pagina5',
            name='icon',
        ),
    ]
