# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180412_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina6',
            name='icon',
        ),
    ]
