# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_pagina6_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina2',
            new_name='Cabezera',
        ),
        migrations.RenameModel(
            old_name='Pagina1',
            new_name='Portada',
        ),
    ]
