# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180417_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=20)),
                ('img', models.ImageField(height_field=607, upload_to=None, width_field=363)),
            ],
        ),
        migrations.DeleteModel(
            name='Cabezera',
        ),
    ]
