# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180423_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulocodigo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='modulocodigo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modulocodigo',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
