# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180423_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='body',
            new_name='descripcion',
        ),
    ]
