# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180423_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='titulo',
            new_name='titulopost',
        ),
        migrations.AddField(
            model_name='modulopie',
            name='titulopost',
            field=models.CharField(default=32, max_length=250),
            preserve_default=False,
        ),
    ]
