# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 10:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180424_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
