# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 10:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180424_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 1000 car\xe1cteres.', max_length=1000, verbose_name='Descripci\xf3n de la Noticia'),
        ),
        migrations.AlterField(
            model_name='modulocodigo',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 1000 car\xe1cteres.', max_length=1000, verbose_name='Descripci\xf3n de la Noticia'),
        ),
        migrations.AlterField(
            model_name='moduloimagen',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 1000 car\xe1cteres.', max_length=1000, verbose_name='Descripci\xf3n de la Noticia'),
        ),
        migrations.AlterField(
            model_name='moduloitem',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 50 car\xe1cteres.', max_length=50, verbose_name='Descripci\xf3n del producto'),
        ),
        migrations.AlterField(
            model_name='moduloitem2',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 40 car\xe1cteres.', max_length=40, verbose_name='Descripci\xf3n 1 del producto'),
        ),
        migrations.AlterField(
            model_name='moduloitem2',
            name='descripcion1',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 40 car\xe1cteres.', max_length=40, verbose_name='Descripci\xf3n 2 del producto'),
        ),
        migrations.AlterField(
            model_name='moduloitem2',
            name='descripcion2',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 40 car\xe1cteres.', max_length=40, verbose_name='Descripci\xf3n 3 del producto'),
        ),
        migrations.AlterField(
            model_name='modulopie',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Introduzca una descripci\xf3n, m\xe1ximo 1500 car\xe1cteres.', max_length=1500, verbose_name='Descripci\xf3n del Pie de P\xe1gina'),
        ),
    ]
